# Generated by Django 4.0.3 on 2022-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberdata',
            name='price',
        ),
        migrations.AddField(
            model_name='memberdata',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='firstname',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='lastname',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
