# Generated by Django 4.0.3 on 2022-03-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_remove_memberdata_member_remove_memberdata_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='email',
            field=models.CharField(default='email', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='firstname',
            field=models.CharField(default='First name', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='lastname',
            field=models.CharField(default='Last name', max_length=30),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='username',
            field=models.CharField(default='User name', max_length=50, primary_key=True, serialize=False),
        ),
    ]
